# language.py

class Language:
    def __init__(self):
        self.current_language = 'English'  # 默认语言
        self.languages = {
            'English': {
                'ok': 'OK',
                'cancel': 'Cancel',
                'warning': 'Warning',
                'error': 'Error',
                'success': 'Success',
                'confirm': 'Confirm',
                'title': 'ZHTLLM RAG Project Interface',
                'create_or_delete_project': 'Create or Delete Project',
                'create_project': 'Create a project',
                'search_projects': 'Search for projects',
                'log_view': 'Log View',
                'meeting_mode': 'Meeting mode',
                'history_list': 'History list',
                'build_rag': '1. Build the RAG',
                'project_desc': 'Project Description: No project selected.',
                'add_files': 'Add files',
                'configure_build': 'Configure',
                'run_build': 'Run Build',
                'query': '2. Query',
                'query_input': 'Ask any questions:',
                'configure_query': 'Configure',
                'run_query': 'Run Query',
                'output': 'Output',
                'settings': 'Settings',
                'build_error_no_files': 'No files selected for build. Use \'Add files\' first.',
                'build_error_no_project': 'No project selected. Please create or select a project first.',
                'query_error_empty': 'Query is empty.',
                'query_error_no_project': 'No project selected. Please create or select a project first.',
                'build_finished': '--- Build Finished ---',
                'search_finished': '--- Search Finished ---',
                'error_occurred': '--- ERROR ---',
                'active_project': 'Active project set to: \'{}\'',
                'settings_updated': 'Settings updated.',
                'files_selected': 'Files selected for the next build.',
                'build_config_updated': 'Build configuration updated: Mode set to {}, model set to {}.',
                'query_config_updated': 'Query configuration updated: Mode set to {}, model set to {}.',
                'application_started': 'Application started',
                'application_started_complete': 'Application started successfully',
                'log_view_title': 'View Logs',
                'project_manager_title': 'Project Management',
                'create_project_success': 'Project \'{}\' created successfully',
                'create_project_failure': 'Failed to create project',
                'delete_project': 'Delete Project',
                'delete_project_confirm': 'Are you sure you want to delete the project \'{}\'? This operation cannot be undone.',
                'delete_project_success': 'Project deleted successfully',
                'delete_project_failure': 'Failed to delete project',
                'select_project_first': 'Please select a project first',
                'enter_project_name': 'Enter project name:',
                'project_exists': 'Project \'{}\' already exists',
                'confirm_delete': 'Confirm Deletion',
                'close': 'Close',
                'log_file_not_found': 'Log file not found',
                'error_reading_log': 'Error reading log: {}',
                'add_files_to_project': 'Add Files to Project',
                'add_text_files_btn': 'Add Text Files',
                'add_dialogue_audio_btn': 'Add Dialogue Audio',
                'add_speaker_sample_btn': 'Add Speaker Sample',
                'files_included_in_build': 'Files included in build:',
                'character_registration': 'Character Registration',
                'speaker_name_label': 'Speaker Name:',
                'select_text_files_title': 'Select Text Files',
                'text_files_filter': 'Text files (*.txt *.pdf *.docx *.md)',
                'select_dialogue_audio_title': 'Select Dialogue Audio',
                'select_speaker_sample_title': 'Select Sample Audio for {}',
                'input_error': 'Input Error',
                'enter_speaker_name': 'Please enter a speaker name first',
                'build_configuration': 'Build Configuration',
                'query_configuration': 'Query Configuration',
                'reasoning_label': 'Reasoning Mode',
                'model_label': 'Model',
                'custom_model_details': 'Custom Model Details',
                'model_name_label': 'Model Name:',
                'api_base_label': 'API Base:',
                'api_key_label': 'API Key:',
                'custom': 'Custom...',
                'custom_model_name_empty': 'Custom model name cannot be empty',
                'custom_cloud_model_requirements': 'Cloud models require both API Base and API Key',
                'inference_mode_label': 'Inference Mode',
                'cloud_api_base_label': 'Cloud API Base',
                'cloud_api_key_label': 'Cloud API Key',
                'cloud_model_label': 'Cloud Model',
                'local_api_base_label': 'Local API Base',
                'local_model_label': 'Local Model',
                'embedding_model_label': 'Embedding Model',
                'embedding_api_base_label': 'Embedding API Base',
                'build_started': 'Building project \'{}\'...',
                'query_started': 'Querying project \'{}\' with query: \'{}\'...',
                'build_complete': 'Build process completed',
                'query_complete': 'Query completed: {}',
                'task_error': 'Task failed with error: {}',
                # Meeting Mode translations
                'meeting_mode_title': 'Meeting Mode',
                'add_speaker_button': 'Add Speaker',
                'speaker_file_label': 'Speaker Sample File:',
                'no_file_selected': 'No file selected.',
                'recording_status_label': 'Recording Status:',
                'elapsed_time_label': 'Elapsed Time:', # 新增
                'start_recording_button': 'Start Recording',
                'stop_recording_button': 'Stop Recording',
                'build_interval_label': 'Build Interval (minutes):',
                'start_auto_build_button': 'Start Auto Build',
                'stop_auto_build_button': 'Stop Auto Build',
                'recording_saved_to': 'Recording saved to {}',
                'auto_build_started': 'Auto build started for project \'{}\' every {} minutes.',
                'auto_build_stopped': 'Auto build stopped for project \'{}\'.',
                'speaker_and_file_required': 'Please select a speaker and a sample file.',
                'recording_in_progress': 'Recording...',
                'not_recording': 'Not Recording',
                'invalid_build_interval': 'Invalid build interval. Please enter a positive number.',
                'no_mic_found': 'No default microphone found. Please check your system settings.',
                'use_mock_audio_prompt': 'No microphone detected. Would you like to use a pre-recorded audio file to simulate recording?',
                'select_mock_audio_title': 'Select Mock Audio File',
                'mock_audio_selected': 'Mock audio file selected for simulation: {}',
            },
            '中文': {
                'ok': '确定',
                'cancel': '取消',
                'warning': '警告',
                'error': '错误',
                'success': '成功',
                'confirm': '确认',
                'title': 'ZHTLLM 检索增强生成项目界面',
                'create_or_delete_project': '创建或删除项目',
                'create_project': '创建项目',
                'search_projects': '搜索项目',
                'log_view': '日志查看',
                'meeting_mode': '会议模式',
                'history_list': '历史项目列表',
                'build_rag': '1. 构建RAG',
                'project_desc': '项目描述: 未选择项目。',
                'add_files': '添加文件',
                'configure_build': '配置',
                'run_build': '运行构建',
                'query': '2. 查询',
                'query_input': '输入您的问题:',
                'configure_query': '配置',
                'run_query': '运行查询',
                'output': '输出',
                'settings': '设置',
                'build_error_no_files': '未选择用于构建的文件。请先使用"添加文件"。',
                'build_error_no_project': '未选择项目。请先创建或选择一个项目。',
                'query_error_empty': '查询内容为空。',
                'query_error_no_project': '未选择项目。请先创建或选择一个项目。',
                'build_finished': '--- 构建完成 ---',
                'search_finished': '--- 搜索完成 ---',
                'error_occurred': '--- 错误 ---',
                'active_project': '当前活动项目: \'{}\'',
                'settings_updated': '设置已更新。',
                'files_selected': '已为下一次构建选择文件。',
                'build_config_updated': '构建配置已更新: 模式设置为 {}, 模型设置为 {}.',
                'query_config_updated': '查询配置已更新: 模式设置为 {}, 模型设置为 {}.',
                'application_started': '应用程序已启动',
                'application_started_complete': '应用程序已成功启动',
                'log_view_title': '查看日志',
                'project_manager_title': '项目管理',
                'create_project_success': '项目 \'{}\' 已成功创建',
                'create_project_failure': '创建项目失败',
                'delete_project': '删除项目',
                'delete_project_confirm': '您确定要删除项目 \'{}\' 吗？此操作无法撤销。',
                'delete_project_success': '项目已成功删除',
                'delete_project_failure': '删除项目失败',
                'select_project_first': '请先选择一个项目',
                'enter_project_name': '输入项目名称:',
                'project_exists': '项目 \'{}\' 已存在',
                'confirm_delete': '确认删除',
                'close': '关闭',
                'log_file_not_found': '日志文件未找到',
                'error_reading_log': '读取日志时出错: {}',
                'add_files_to_project': '向项目添加文件',
                'add_text_files_btn': '添加文本文件',
                'add_dialogue_audio_btn': '添加对话音频',
                'add_speaker_sample_btn': '添加说话者样本',
                'files_included_in_build': '构建中包含的文件:',
                'character_registration': '角色注册',
                'speaker_name_label': '说话者名称:',
                'select_text_files_title': '选择文本文件',
                'text_files_filter': '文本文件 (*.txt *.pdf *.docx *.md)',
                'select_dialogue_audio_title': '选择对话音频',
                'select_speaker_sample_title': '为 {} 选择样本音频',
                'input_error': '输入错误',
                'enter_speaker_name': '请先输入说话者名称',
                'build_configuration': '构建配置',
                'query_configuration': '查询配置',
                'reasoning_label': '推理模式',
                'model_label': '模型',
                'custom_model_details': '自定义模型详情',
                'model_name_label': '模型名称:',
                'api_base_label': 'API 基础地址:',
                'api_key_label': 'API 密钥:',
                'custom': '自定义...',
                'custom_model_name_empty': '自定义模型名称不能为空',
                'custom_cloud_model_requirements': '云模型需要API基础地址和API密钥',
                'inference_mode_label': '推理模式',
                'cloud_api_base_label': '云API基础地址',
                'cloud_api_key_label': '云API密钥',
                'cloud_model_label': '云模型',
                'local_api_base_label': '本地API基础地址',
                'local_model_label': '本地模型',
                'embedding_model_label': '嵌入模型',
                'embedding_api_base_label': '嵌入API基础地址',
                'build_started': '正在构建项目 \'{}\'...',
                'query_started': '正在使用查询: \'{}\' 查询项目 \'{}\'...',
                'build_complete': '构建过程已完成',
                'query_complete': '查询已完成: {}',
                'task_error': '任务失败，错误信息: {}',
                # 会议模式翻译
                'meeting_mode_title': '会议模式',
                'add_speaker_button': '添加说话人',
                'speaker_file_label': '说话人音频样本:',
                'no_file_selected': '未选择文件。',
                'recording_status_label': '录制状态:',
                'elapsed_time_label': '已录制时间:', # 新增
                'start_recording_button': '开始录制',
                'stop_recording_button': '停止录制',
                'build_interval_label': '构建间隔 (分钟):',
                'start_auto_build_button': '开始自动构建',
                'stop_auto_build_button': '停止自动构建',
                'recording_saved_to': '录音已保存至 {}',
                'auto_build_started': '项目 \'{}\' 的自动构建已启动，每 {} 分钟一次。',
                'auto_build_stopped': '项目 \'{}\' 的自动构建已停止。',
                'speaker_and_file_required': '请先选择说话人和样本文件。',
                'recording_in_progress': '录音中...',
                'not_recording': '未录音',
                'invalid_build_interval': '无效的构建间隔。请输入一个正数。',
                'no_mic_found': '未找到默认麦克风。请检查您的系统设置。',
                'use_mock_audio_prompt': '未检测到麦克风。您想使用一个预存的音频文件来模拟录音吗？',
                'select_mock_audio_title': '选择模拟音频文件',
                'mock_audio_selected': '已选择用于模拟的音频文件: {}',
            }
        }

    def set_language(self, language):
        if language in self.languages:
            self.current_language = language
        else:
            print(f"Error: Language '{language}' not supported.")

    def get_language_list(self):
        return list(self.languages.keys())

    def get(self, key):
        return self.languages[self.current_language].get(key, key)

# 创建单例语言实例
lang = Language()